In [128]:
!pip install numpy
!pip install pandas
import numpy as np
import pandas as pd

Requirement already satisfied: numpy in /Users/moriyasutatsuzawa/.pyenv/versions/3.8.3/lib/python3.8/site-packages (1.19.0)
WARNING: You are using pip version 19.2.3, however version 20.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Requirement already satisfied: pandas in /Users/moriyasutatsuzawa/.pyenv/versions/3.8.3/lib/python3.8/site-packages (1.0.5)
Requirement already satisfied: python-dateutil>=2.6.1 in /Users/moriyasutatsuzawa/.pyenv/versions/3.8.3/lib/python3.8/site-packages (from pandas) (2.8.1)
Requirement already satisfied: pytz>=2017.2 in /Users/moriyasutatsuzawa/.pyenv/versions/3.8.3/lib/python3.8/site-packages (from pandas) (2020.1)
Requirement already satisfied: numpy>=1.13.3 in /Users/moriyasutatsuzawa/.pyenv/versions/3.8.3/lib/python3.8/site-packages (from pandas) (1.19.0)
Requirement already satisfied: six>=1.5 in /Users/moriyasutatsuzawa/.pyenv/versions/3.8.3/lib/python3.8/site-packages (from python-dateutil>=2.6.1->pandas) (1.15.0)
WARNING: You are using pip version 19.2.3, however version 20.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

In [139]:
df1 = pd.read_csv("c1.csv",encoding="cp932")

In [140]:
df1.head(2)

   PassengerId  Pclass Name
0            1       1   田中
1            2       2   佐藤

In [141]:
df1["twin"] = np.zeros(len(df1))

In [143]:
def dup(k):
    return len(k) != len(set(k))

b = pd.DataFrame(df1.groupby("Pclass")["Name"].apply(dup))
b = b.reset_index(inplace = False)
b = b.rename(columns={'Name': 'twin'})
b

   Pclass   twin
0       1   True
1       2  False
2       3  False
3       4  False
4       5  False
5       6  False

In [146]:
df = pd.merge(df1,b, on = "Pclass")
df

   PassengerId  Pclass Name  twin_x  twin_y
0            1       1   田中     0.0    True
1            4       1   田中     0.0    True
2            2       2   佐藤     0.0   False
3            3       2   鈴木     0.0   False
4            5       6   島田     0.0   False
5            6       5   立澤     0.0   False
6            7       4   山口     0.0   False
7            8       3   佐藤     0.0   False
8            9       3   常田     0.0   False

In [113]:
df1.groupby("Pclass")["Name"].apply(lambda x: ','.join(x))

Pclass
1    田中,田中
2    佐藤,鈴木
3    佐藤,常田
4       山口
5       立澤
6       島田
Name: Name, dtype: object

In [ ]:
df = pd.merge(df1,a)

In [60]:
#v1とv2をvlookupでくっつける
for i in range(len(df1)):
    for u in range(len(df1)):
        if not df1.iloc[i,2] == df1.iloc[u,2]:
            df1.iloc[i,0] = df1.iloc[i,3] + 0
        else:
            df1.iloc[i,3] =  df1.iloc[i,3] + 1

In [59]:
df1.twin.value_counts()

1.0    366
2.0     52
Name: twin, dtype: int64